### ISSUE TITLE
Comentarios/Mejoras

### ISSUE THREAD

**Issue by eisenheimjelid** [javleds/python_basic_first_challenge#1]
Bajé el código y solo le tuve que hacer un cambio en `src/input_utils.py`:
`from .number_utils import is_float`
en lugar de 
`from number_utils import is_float`

Esto porque me marcaba este error:
```
======================================================================
ERROR: test_input_utils (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_input_utils
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/david/Projects/jelid/python_basic_first_challenge/tests/test_input_utils.py", line 3, in <module>
    from src.input_utils import ask_for_number
  File "/home/david/Projects/jelid/python_basic_first_challenge/src/input_utils.py", line 1, in <module>
    from number_utils import is_float
ModuleNotFoundError: No module named 'number_utils'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

```

Luego, ejecutando el siguiente comando `python3 -m unittest tests/test_input_utils.py` me responde lo siguiente:
```
...
----------------------------------------------------------------------
Ran 3 tests in 0.001s

OK

```
![Screenshot from 2021-05-19 08-11-54](https://user-images.githubusercontent.com/505999/118818590-1bfcb800-b87a-11eb-86c1-c6727427aabe.png)

Yo veo que funciona bien tu test input, solo quité la anotación y lo hice directo. Pero cuando le pongo una letra en lugar de un número, se queda en un ciclo infinito. Yo siempre recomiendo usar `try ... except ...` para tener un mejor control de excepciones, en lugar del `while True` que estas usando, porque aunque la experiencia del usuario puede ser mejor dado que el programa no avanza a menos de el usuario ingrese un valor correcto, ya no es tan amigable con las pruebas. Yo lo programaría así:

```python
def ask_for_number(message: str) -> float:
    value = None
    try:
        while value is None:
            value = input(message)
            value = float(value)
    except Exception as err:
        print(str(err))
        print('Invalid character, please type a number. Or press `q` to exit')
    return value
```

De esa forma, cuando ejecuto la prueba no se queda en un ciclo infinito cuando meten una letra en lugar de un número y puedes hacer más robusta tu prueba al considerar casos de errores controlados:

```
$ python3 -m unittest tests/test_input_utils.py 
..could not convert string to float: 
Invalid character, please type a number. Or press `q` to exit
F
======================================================================
FAIL: test_multiple_cases (tests.test_input_utils.TestInputUtils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/david/Projects/jelid/python_basic_first_challenge/tests/test_input_utils.py", line 19, in test_multiple_cases
    self.assertEqual(ask_for_number(''), 10.0)
AssertionError: '' != 10.0

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=1)
```

Aunque ya para concluir, lo más importante es primero preguntar ¿qué quieres probar? es conveniente hacer pruebas separadas, lógica e interacción con el usuario. Me refiero a que si deseas probar tu lógica, separa esa parte dentro de tu código y luego si quieres hacer pruebas de la interacción con el usuario, solo te enfoques a eso. Por último, te recomiendo estos enlaces:
- https://docs.python.org/3/library/unittest.html#organizing-test-code
- https://docs.python.org/3/library/unittest.mock.html#patch-builtins
- https://forum.learncodethehardway.com/t/testing-input-and-print/1757/3

El primer enlace te dice como "organizar" mejor tu código, por lo que preguntabas de incluir el `if __name__ == '__main__':` es precisamente cuando ejecutas la prueba directa `python3 test/test_input_utils.py` en lugar de `python3 -m unittest tests/test_input_utils.py`, pero lo puedes organizar en un solo archivo como una "suite" de pruebas, y mandas a llamar desde ahí todas las pruebas que quieres hacer, y solo ejecutar algo como `python3 tests/suite.py` y eso te permite hacerlo más "sencillo".

A ver si luego comparto en phpmx algunos tips con GitHub Actions: https://github.com/marketplace/actions/python-unit-test

**Comment by javleds** [comment]
Gracias por el aporte @eisenheimjelid la utilidad de pedir un número no es sencilla, la lógica es la siguiente:

- Solicitar un valor numérico al usuario.
- Si el valor ingresado no es numérico, solicitar una nueva entrada (hasta que sea numérica).
- Salir del programa presionando `q` si es necesario.

Lo que me gustaría probar es:
- [x] Que al ingresar un número, el ciclo se detenga y me egrese ese número.
- [ ] Que al ingresar un valor no numérico me imprima en consola que el valor no es correcto y que me pregunte de nuevo.
- [ ] Que al presionar la letra `q` se cierre el programa.

Me parece que el escenario complicado es el segundo.

**Comment by javleds** [comment]
@eisenheimjelid Por qué fue necesario agregar el `dot` al inicio del script a importar?

```
.number_utils
```

**Comment by eisenheimjelid** [comment]
El error esta ahí `ModuleNotFoundError: No module named 'number_utils'` como no lo encuentra, lo agregué.

La forma en que importa las referencias python es por medio de las carpetas en el sistema de archivos, yo uso Linux, y es más estricto con ese tipo de cosas.

Referencia:
- https://docs.python.org/3/reference/import.html#regular-packages
